# Generated by Django 6.0.5 on 2026-05-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_equipment', models.IntegerField()),
                ('assigned_count', models.IntegerField()),
                ('available_count', models.IntegerField()),
                ('popular_categories', models.JSONField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
