# Generated by Django 5.1 on 2025-06-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='condition',
            field=models.CharField(choices=[('Исправно', 'Исправно'), ('Нужен ремонт', 'Нужен ремонт'), ('Неисправно', 'Неисправно')], default='Исправно', max_length=50, verbose_name='Состояние'),
        ),
    ]
