# Generated by Django 5.1 on 2025-06-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='office',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Кабинет'),
        ),
    ]
