# Generated by Django 5.1 on 2025-06-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='condition',
            field=models.CharField(choices=[('Отличное', 'Отличное'), ('Хорошее', 'Хорошее'), ('Удовлетворительное', 'Удовлетворительное'), ('Нужен ремонт', 'Нужен ремонт'), ('Неисправно', 'Неисправно')], default='Исправно', max_length=50, verbose_name='Состояние'),
        ),
    ]
