# Generated by Django 5.1 on 2025-05-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_savedtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtable',
            name='imported_devices',
            field=models.ManyToManyField(blank=True, to='table.importeddevice'),
        ),
        migrations.AddField(
            model_name='savedtable',
            name='table_type',
            field=models.CharField(choices=[('devices', 'Устройства'), ('imported', 'Импортированные устройства')], default='devices', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedtable',
            name='devices',
            field=models.ManyToManyField(blank=True, to='table.device'),
        ),
    ]
