# Generated by Django 5.1 on 2025-05-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_savedtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='acceptance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата принятия к учету'),
        ),
        migrations.AddField(
            model_name='device',
            name='book_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Балансовая стоимость'),
        ),
        migrations.AddField(
            model_name='device',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
