# Generated by Django 5.1 on 2025-05-21 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_savedtable_imported_devices_savedtable_table_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedtable',
            options={'verbose_name': 'Сохраненная таблица', 'verbose_name_plural': 'Сохраненные таблицы'},
        ),
    ]
