# Generated by Django 5.1 on 2025-05-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_savedtable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedtable',
            options={},
        ),
        migrations.RemoveField(
            model_name='savedtable',
            name='imported_devices',
        ),
        migrations.RemoveField(
            model_name='savedtable',
            name='table_type',
        ),
        migrations.AlterField(
            model_name='savedtable',
            name='devices',
            field=models.ManyToManyField(to='table.importeddevice'),
        ),
    ]
