# Generated by Django 5.1 on 2025-05-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_device_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, choices=[('office_400p', 'Кабинет 400п'), ('office_400l', 'Кабинет 400л'), ('office_400a', 'Кабинет 400а'), ('office_401', 'Кабинет 401'), ('office_402', 'Кабинет 402'), ('office_402a', 'Кабинет 402а'), ('office_403a', 'Кабинет 403а'), ('office_403p', 'Кабинет 403п'), ('office_404', 'Кабинет 404'), ('office_406', 'Кабинет 406'), ('office_408', 'Кабинет 408'), ('office_410', 'Кабинет 410'), ('server_room', 'Серверная'), ('warehouse', 'Склад')], max_length=50, null=True, verbose_name='Расположение'),
        ),
    ]
