# Generated by Django 5.1 on 2025-05-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_alter_device_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, choices=[('office_101', 'Кабинет 101'), ('office_102', 'Кабинет 102'), ('office_201', 'Кабинет 201'), ('office_202', 'Кабинет 202'), ('server_room', 'Серверная'), ('warehouse', 'Склад')], max_length=50, null=True, verbose_name='Расположение'),
        ),
    ]
