# Generated by Django 5.1 on 2025-06-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_alter_device_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, choices=[('office400p', 'Кабинет 400п'), ('office400l', 'Кабинет 400л'), ('office400a', 'Кабинет 400а'), ('office401', 'Кабинет 401'), ('office402', 'Кабинет 402'), ('office402a', 'Кабинет 402а'), ('office403a', 'Кабинет 403а'), ('office403p', 'Кабинет 403п'), ('office404', 'Кабинет 404'), ('office406', 'Кабинет 406'), ('office408', 'Кабинет 408'), ('office410', 'Кабинет 410'), ('server_room', 'Серверная'), ('warehouse', 'Склад')], max_length=50, null=True, verbose_name='Расположение'),
        ),
    ]
